version: '3.8'
services:
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/
      - ./volumes/pgbackrest/:/var/lib/pgbackrest/
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      start_period: 30s

  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z
    ports:
    - "443:443"
    - "9001:9001"
    command: server /data/ --certs-dir /certs --address ':443' --console-address ':9001'
    volumes:
      - ./volumes/minio/data/:/data/
      - ./minio/certs/:/certs/
