version: '3.8'
services:
  postgres1:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      START_SUPERCRONIC: 1

      PGBACKREST_REPO1_PATH: "/repo2"
      PGBACKREST_REPO1_S3_ENDPOINT: minio
      PGBACKREST_REPO1_S3_BUCKET: pgbackrest
      PGBACKREST_REPO1_S3_VERIFY_TLS: n
      PGBACKREST_REPO1_S3_KEY: minioadmin
      PGBACKREST_REPO1_S3_KEY_SECRET: minioadmin
      PGBACKREST_REPO1_S3_REGION: us-east-1
      PGBACKREST_REPO1_RETENTION_FULL: 2

    volumes:
      - ./volumes/postgres1/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      start_period: 30s

  postgres2:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres2.conf:/etc/postgresql/postgresql.conf
      - ./volumes/postgres2/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      start_period: 30s

  minio:
    image: minio/minio:RELEASE.2023-09-30T07-02-29Z
    hostname: pgbackrest.minio
    ports:
    - "443:443"
    - "9001:9001"
    environment:
      MINIO_REGION: us-east-1
      MINIO_DOMAIN: minio
    command: server /data/ --certs-dir /certs --address ':443' --console-address ':9001'
    volumes:
      - ./volumes/minio/data/:/data/
      - ./minio/certs/:/certs/
