version: '3.8'
services:
  postgres1:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      ENABLE_PGBACKREST_BACKUP: 1
      # DISABLE_SUPERCRONIC: 1

      # Configuration for local Minio bucket instance
      PGBACKREST_REPO1_PATH: "/repo"
      PGBACKREST_REPO1_S3_ENDPOINT: minio
      PGBACKREST_REPO1_S3_BUCKET: pgbackrest
      PGBACKREST_REPO1_S3_VERIFY_TLS: n
      PGBACKREST_REPO1_S3_KEY: minioadmin
      PGBACKREST_REPO1_S3_KEY_SECRET: minioadmin
      PGBACKREST_REPO1_S3_REGION: us-east-1
      PGBACKREST_REPO1_RETENTION_FULL: 2

      # Configuration for Backblaze remote bucket
      # See ./terraform-backblaze to create Backblaze bucket
      # PGBACKREST_REPO1_PATH: "/repo"
      # PGBACKREST_REPO1_S3_URI_STYLE: "path"
      # PGBACKREST_REPO1_S3_ENDPOINT: s3.eu-central-003.backblazeb2.com
      # PGBACKREST_REPO1_S3_BUCKET: pgbackrest-backup-bucket
      # PGBACKREST_REPO1_S3_VERIFY_TLS: y
      # PGBACKREST_REPO1_S3_KEY: ${B2_APPLICATION_KEY_ID}
      # PGBACKREST_REPO1_S3_KEY_SECRET: ${B2_APPLICATION_KEY}
      # PGBACKREST_REPO1_S3_REGION: s3.eu-central-003
      # PGBACKREST_REPO1_RETENTION_FULL: 2

      # Configuration for Scaleway remote bucket
      # See ./terraform-scaleway to create Scaleway bucket
      # PGBACKREST_REPO1_PATH: "/repo"
      # PGBACKREST_REPO1_S3_URI_STYLE: "host"
      # PGBACKREST_REPO1_S3_ENDPOINT: s3.fr-par.scw.cloud
      # PGBACKREST_REPO1_S3_BUCKET: pgbackrest-backup-bucket
      # PGBACKREST_REPO1_S3_VERIFY_TLS: y
      # PGBACKREST_REPO1_S3_KEY: ${SCW_ACCESS_KEY}
      # PGBACKREST_REPO1_S3_KEY_SECRET: ${SCW_SECRET_KEY}
      # PGBACKREST_REPO1_S3_REGION: fr-par
      # PGBACKREST_REPO1_RETENTION_FULL: 2

    volumes:
      - ./volumes/postgres1/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      start_period: 30s

  postgres2:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

      # Configuration for local Minio instance
      PGBACKREST_REPO1_PATH: "/repo"
      PGBACKREST_REPO1_S3_ENDPOINT: minio
      PGBACKREST_REPO1_S3_BUCKET: pgbackrest
      PGBACKREST_REPO1_S3_VERIFY_TLS: n
      PGBACKREST_REPO1_S3_KEY: minioadmin
      PGBACKREST_REPO1_S3_KEY_SECRET: minioadmin
      PGBACKREST_REPO1_S3_REGION: us-east-1
      PGBACKREST_REPO1_RETENTION_FULL: 2

      # Configuration for Backblaze remote bucket
      # PGBACKREST_REPO1_PATH: "/repo"
      # PGBACKREST_REPO1_S3_ENDPOINT: backblazeb2.com
      # PGBACKREST_REPO1_S3_BUCKET: pgbackrest-backup-bucket
      # PGBACKREST_REPO1_S3_VERIFY_TLS: y
      # PGBACKREST_REPO1_S3_KEY: ${B2_APPLICATION_KEY_ID}
      # PGBACKREST_REPO1_S3_KEY_SECRET: ${B2_APPLICATION_KEY}
      # PGBACKREST_REPO1_S3_REGION: s3.eu-central-003
      # PGBACKREST_REPO1_RETENTION_FULL: 2

      # Configuration for Scaleway remote bucket
      # PGBACKREST_REPO1_PATH: "/repo"
      # PGBACKREST_REPO1_S3_URI_STYLE: "host"
      # PGBACKREST_REPO1_S3_ENDPOINT: s3.fr-par.scw.cloud
      # PGBACKREST_REPO1_S3_BUCKET: pgbackrest-backup-bucket
      # PGBACKREST_REPO1_S3_VERIFY_TLS: y
      # PGBACKREST_REPO1_S3_KEY: ${SCW_ACCESS_KEY}
      # PGBACKREST_REPO1_S3_KEY_SECRET: ${SCW_SECRET_KEY}
      # PGBACKREST_REPO1_S3_REGION: fr-par
      # PGBACKREST_REPO1_RETENTION_FULL: 2

    volumes:
      - ./volumes/postgres2/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      start_period: 30s

  minio:
    image: minio/minio:RELEASE.2023-09-30T07-02-29Z
    hostname: pgbackrest.minio
    ports:
    - "443:443"
    - "9001:9001"
    environment:
      MINIO_REGION: us-east-1
      MINIO_DOMAIN: minio
    command: server /data/ --certs-dir /certs --address ':443' --console-address ':9001'
    volumes:
      - ./volumes/minio/data/:/data/
      - ./minio/certs/:/certs/
