version: '3.8'
services:
  postgres3:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

      PGBACKREST_REPO1_PATH: "/repo"
      PGBACKREST_REPO1_S3_URI_STYLE: "host"
      PGBACKREST_REPO1_S3_ENDPOINT: s3.fr-par.scw.cloud
      PGBACKREST_REPO1_S3_BUCKET: pgbackrest-backup-bucket2
      PGBACKREST_REPO1_S3_VERIFY_TLS: y
      PGBACKREST_REPO1_S3_KEY: ${SCW_ACCESS_KEY}
      PGBACKREST_REPO1_S3_KEY_SECRET: ${SCW_SECRET_KEY}
      PGBACKREST_REPO1_S3_REGION: fr-par
      PGBACKREST_REPO1_RETENTION_FULL: 2

    volumes:
      - ./volumes/postgres3/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      start_period: 30s

